sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-635.pdf --upload --lsstdoc LDM-635.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="ldm-635"
    # LSST the Docs credentials
    - secure: "DQmk031ru9uCh39nEC0WI373JLYmn/FmrvNMnkVftMFLchymB/3tuUgjslnB3GNv5kyTlW2JuC53V7wiOgLUjtEMkRoJvEKscYqAotpFvtXoKL1iJDLEaleaMT+tMfG8H+ZpWhR2RXcFtUVUxE9U7FROpwDaH/n5c9DGAsG3dl8q3kDT0GkL6NSyaEURrejQ66k0JpfNCS+tMd5B2Ql4TSrburUqhNtPvRJ6mVVzMxYITUIhHGWoD0Y/apa5JcWTerQ2XgFo87IwLEUPBxeXF+88LbNEWAiIahK0780kYH3SoxeFioWM6TNe8nS5Q4PnjekWoyEjCpAv+GdOWIucoDkptiIEdf5lS6Q3Yzl20zg+bqo6MDZbvs7CBZmGlL9x2NZmxbS2HrM36uRCg8hkPPgqwVA5JvEDlADViubujAAjwWJVnktpESpdxNw0PHK4RWgPdSTHeLIZCozm0XxRBH1Sh8DPmaY058wAVDXvJhehpOSk1fFS6fCG5MDKEF+XV1B6gomcV0xbHd7+ZppRqBAkd/1mcB0Hm7WMbau8UYNOFjSh+GiXLXaPWsRYU6IlwJfUH37z2BNEHD7kgw6eko3mdZy+AV0nVYCi7hD03O78qsBGfZ6GAns5x7JZtvT0N1MfUGk3mfQvHln55IzNvUp8T7LLUYZV4B15dK87lVc="
    - secure: "hD4cMuzt1jPQN8Q1Q/S4Pg77XLdu11KU5q5GmMpIWMkxEIpOJ6ZIgQCvGOhMId93xufZW051AvR/90NkvPbX1mrBPtQAjYb+jEI2rXSa58O9jduyf7XK4SyJXMCrhRP8vJj683Vbc/J2SKIJFufiijB3b34v/1dC5Ru1uDBTbnL0HEG+jplx5jjRWAg+i/Sj9ldAsRNEM4xiwOyEkFtFJr7McrIhPkotusGtc+gJUvns0aPznnbhtMFSM10jkPzHy94hk/00a9uKJxlLZ2KBVNfmnhIeHE1FX0ZYBGbYlGGohqjHEbNnI2NNoLlQYGUi8+MCvCv0OOFySKbCAx8f4Pc/mHp/fmv/KcfF3+dUlAT0/oBIpBgUjDb5v6TF6Ud8UMGHn+euC5MnmUbHUfiIXeh+VW/iloKAfrZXSEfqQ8adyNLD170u1feqjzOCHRLs8JFvRGRzBcTyCOWNNXSLqgPl5A0bY5FQ5iKCGqj9/hb97iqzEz0WcT/vnThXrIg+KvoNSkG4UU63a8ZZWuI45OaBwqVGAPpaypFZqYCTo599nh9STljvBB92/8NZxW0el2LdvjkUWL7EdJqkzUuEl381KOAbiRH317q5hjHsPqMe1gBzHj+Qs33TouJX5dnYG6aCukj2UsHXTtka9XL4Cb9+1pX8M9uCVkTKqIrdyYc="
